core/urls.py
from django.urls import path, include
from core import views


urlpatterns = [
    # Home url
    path('',views.Home, name='Home'),
    path('Not_Found/',views.Not_Found, name='Not_Found'),

    # Store url
    path('Store/',views.product_list_view, name='product_list_view'),

    # Product Detail url
    path('single_product/<pid>/<slug:slug>/',views.product_detail_view, name='product_detail_view'),
    
    # Seller url
    path('All_vendors/',views.All_vendors, name='All_vendors'),

    # Categories
    path('category/',views.Category_list_view, name='Category_list_view'),
    path('category/<int:id>/<slug:slug>/',views.product_by_category, name='product_by_category'),
    path('subcategory/<int:category_id>/<slug:category_slug>/', views.subcategory_view, name='subcategory_view'),

    
    path('products/tag/<slug:tag_slug>/', views.tag_list, name='tags'),

    path("ajax-add-review/<pid>/",views.ajax_add_review, name="ajax-add-review"),
    path("search/", views.search_view, name="search"),
    path("filter-products/", views.filter_product, name="filter-product"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart, name="cart"),
    path("delete_from_cart/", views.delete_from_cart, name="delete_from_cart"),
    path("update_cart/", views.update_cart, name="update_cart"),
    path('set-currency/<str:currency_code>/', views.set_currency, name='set_currency'),
    path("checkout/", views.checkout, name="checkout"),
    #path("save_checkout_info/", views.save_checkout_info, name="save_checkout_info"),
    
    path('payment_view/<oid>/', views.payment_view, name='payment_view'),
    path('place_order/', views.place_order, name="place_order"),
    #path('save_payment_method/', views.save_payment_method, name='save_payment_method'),


    # paypal url
    path("paypal/", include('paypal.standard.ipn.urls')),
    path("payment_completed_view/<oid>/", views.payment_completed_view, name="payment_completed_view"),
    path('payment_failed_view/<str:oid>/', views.payment_failed_view, name='payment_failed_view'),
    path("order_confirmation/<oid>/", views.order_confirmation, name="order_confirmation"),
    path("dashboard/",views.dashboard, name="dashboard"),
    path("dashboard/order/<int:id>",views.order_detail, name="order_detail"),

    # Making date Default
    path("make_address_default/",views.make_address_default, name="make_address_default"),

    # wishlist Page 
    path("wishlist_view/",views.wishlist_view, name="wishlist_view"),
    path("add_to_wishlist/",views.add_to_wishlist, name="add_to_wishlist"),


    # Remove from Wishlist
    path("remove_wishlist/",views.remove_wishlist, name="remove_wishlist"),
    #path('calculate-shipping-fee/', views.calculate_shipping_fee, name='calculate_shipping_fee'),

    # Contact Us Page 
    path("contact/", views.contact, name="contact"),
    path("ajax_contact/", views.ajax_contact, name="ajax_contact"),

    #Platform Settings
    #frequently asked Questions
    path('faq/', views.faq, name='faq'),
    path('policy_privacy/', views.policy_privacy, name='policy_privacy'),
    path('Why_sellonEmariStore/', views.why, name='why'),
    path('return_policy/', views.return_policy, name='return_policy'),

    # Vendor Urls 

    path('vendor_detail/<vid>/', views.vendor_detail_view, name='vendor_detail_view'),
    path('vendor_list/', views.vendor_list, name='vendor_list'),
    path('account_orders_view/', views.account_orders_view, name='account_orders_view'),
    
    

]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView




urlpatterns = [
    # Your non-i18n URLs here
    #path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('Vendors/', include("Vendor.urls")),
    path('NewsLetter/', include('NewsLetter.urls')),
    path('user/', include('userauths.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("AdminPanel/", include('AdminPanel.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from . import views

app_name = 'userauths'

urlpatterns = [
    path('sign-up/',views.register,name='sign-up'),
    path('vendor_register/', views.register_vendor, name='vendor_register'),
    path('custom_login/',views.custom_login,name='custom_login'),
    path('custom_logout/',views.custom_logout,name='custom_logout'), 
    path('activate/<uidb64>/<token>',views.ActivateAccountView.as_view(),name='customeractivate'),
    path('activate/<uidb64>/<token>',views.VendorActivateAccountView.as_view(),name='vendoractivate'), 
    path('request_reset_email/',views.RequestResetEmailView.as_view(),name='request_reset_email'),
    path('set_new_password/<uidb64>/<token>',views.SetNewPasswordView.as_view(),name='set_new_password'),
     path('profile_update/',views.profile_update,name='profile_update'),

]

userauths/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from userauths.forms import RegistrationForm, ProfileForm, VendorRegistrationForm
from .models import Account, Profile
from Vendor.models import Vendor
from django.views.generic import View
from .utils import TokenGenerator, generate_token
from django.contrib import messages, auth
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from django.urls import NoReverseMatch,reverse
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes,force_str,DjangoUnicodeDecodeError
from django.core.mail import send_mail,EmailMultiAlternatives
from django.core.mail import BadHeaderError,send_mail
from django.core import mail
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import PasswordResetTokenGenerator
import requests
import threading
import logging

class EmailThread(threading.Thread):
    def __init__(self, email_message):
        self.email_message = email_message
        threading.Thread.__init__(self)

    def run(self):
        try:
            self.email_message.send(fail_silently=False)
            print("Email sent successfully!")
        except Exception as e:
            logging.error("Failed to send email: %s", e)
            print("Failed to send email:", e)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            
            # Create the user
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password
            )
            user.phone_number = phone_number
            user.is_customer = True
            user.is_active = False
            user.save()

            # Prepare email
            current_site = get_current_site(request)
            email_subject = "Activate your account"
            message = render_to_string('userauths/customeractivate.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': generate_token.make_token(user),
            })
            email_message = EmailMessage(
                email_subject,
                message,
                settings.EMAIL_HOST_USER,
                [email],
            )
            
            # Send email in a separate thread
            EmailThread(email_message).start()

            # Notify user and redirect
            messages.info(request, "Activate by clicking the link sent to your email")
            return redirect('userauths:custom_login')
    else:
        form = RegistrationForm()
         
    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)


def register_vendor(request):
    if request.method == 'POST':
        form = VendorRegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            
            # Create the user
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password
            )

            user.phone_number = phone_number
            user.is_vendor = True  # Set the vendor flag
            user.is_active = False  # Deactivate the user until email confirmation
            user.save()  # Now save the user

            if user.is_vendor:  # Assuming you have a field `is_vendor` in your user model
                    Vendor.objects.create(user=user)

            # Prepare the email for account activation
            current_site = get_current_site(request)
            email_subject = "Activate your account"
            message = render_to_string('userauths/vendoractivate.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': generate_token.make_token(user),
            })
            email_message = EmailMessage(
                email_subject,
                message,
                settings.EMAIL_HOST_USER,  # Added from_email parameter here
                [user.email],
            )
            
            # Send the email in a separate thread
            EmailThread(email_message).start()

            # Notify user and redirect
            messages.info(request, "Activate your account by clicking the link sent to your email")
            return redirect('userauths:custom_login')
    else:
        form = VendorRegistrationForm()

    context = {
        'form': form,
    }
    return render(request, 'userauths/vendor_register.html', context)


class VendorActivateAccountView(View):
    def get(self,request,uidb64,token):
        try:
            uid=force_str(urlsafe_base64_decode(uidb64))
            user=Account.objects.get(pk=uid)
        except Exception as identifier:
            user=None
        if user is not None and generate_token.check_token(user,token):
           user.is_active=True
           user.save() 
           messages.info(request,"account activated succcessfully")
           return redirect('userauths:custom_login')
        return render(request,'activatefail.html')  
    

class ActivateAccountView(View):
    def get(self,request,uidb64,token):
        try:
            uid=force_str(urlsafe_base64_decode(uidb64))
            user=Account.objects.get(pk=uid)
        except Exception as identifier:
            user=None
        if user is not None and generate_token.check_token(user,token):
           user.is_active=True
           user.save() 
           messages.info(request,"account activated succcessfully")
           return redirect('userauths:custom_login')
        return render(request,'activatefail.html')  
      
def custom_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        # Check if the email exists in the user database
        try:
            user = Account.objects.get(email=email)
        except Account.DoesNotExist:
            messages.error(request, 'Failed to login. Email does not exist.')
            return redirect('userauths:custom_login')

        # Authenticate the user
        user = auth.authenticate(request, email=email, password=password)

        if user is not None:
            auth.login(request, user)

            # Check if the user is part of the 'Sellers' group
            if user.groups.filter(name='Sellers').exists():
                return redirect('vendorDashboard')  # Replace with the actual vendor dashboard URL name
            elif user.is_customer:  # Assuming you have a method to identify customer
                return redirect('product_list_view')  # Replace with the actual customer dashboard URL name
            else:
                return redirect('Home')  # Default redirect if no specific role is identified
        else:
            messages.error(request, 'Failed to login. Invalid email or password.')
            return redirect('userauths:custom_login')

    # Add warning message if redirected from a protected page        
    if 'next' in request.GET:
        messages.warning(request, 'You need to log in to access this page.')

    # Get the next URL from the query parameters and pass it to the template
    next_url = request.GET.get('next', '')
    return render(request, 'userauths/custom_login.html', {'next': next_url})


@login_required()
def custom_logout(request):
    auth.logout(request)
    messages.success(request, 'You are Logged out.')
    return render(request, 'userauths/custom_login.html')

class RequestResetEmailView(View):
    def get(self,request):
        return render(request,'userauths/request_reset_email.html')
    
    def post(self,request):
        email=request.POST['email']
        user=Account.objects.filter(email=email)

        if user.exists():
            current_site=get_current_site(request)
            email_subject='[reset your password]'
            message=render_to_string('userauths/reset_user_password.html',
            {
                'domain':'127.0.0.1:8000',
                'uid':urlsafe_base64_encode(force_bytes(user[0].pk)),
                'token':PasswordResetTokenGenerator().make_token(user[0])
            })

            email_message=EmailMessage(email_subject,message,settings.EMAIL_HOST_USER,[email],)
            EmailThread(email_message).start()
            
            messages.info(request,"we have sent you email with instructions on how to reset password")
            return render(request,'userauths/request_reset_email.html')
        
class SetNewPasswordView(View):
    def get(self,request,uidb64,token):
        context={
            'uidb64':uidb64,
            'token':token
        }  
        try:
            user_id=force_str(urlsafe_base64_decode(uidb64))
            user=Account.objects.get(pk=user_id)  

            if not PasswordResetTokenGenerator().check_token(user,token):

templates/userauths/activatefail.html
<h1>Something went wrong</h1>

templates/userauths/custom_login.html
{% extends 'partials/base.html' %} {% load l10n humanize %}
{% load static %}
{% block content %}


        <!-- Begin E-MariStore Breadcrumb Area -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content">
                    <h2>Other</h2>
                    <ul>
                        <li><a href="{% url 'Home' %}">Home</a></li>
                        <li class="active">Login</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- E-MariStore Breadcrumb Area End Here -->
        <!-- Begin E-MariStore Login Register Area -->
        <div class="uren-login-register_area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                        <!-- Login Form s-->
                        <form action="#" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}">
                            <div class="login-form">
                                <h4 class="login-title">Login</h4>
                                <div class="row">
                                    <div class="col-md-12 col-12">
                                        <label>Email Address*</label>
                                        <input type="email" placeholder="Email Address" name="email" required>
                                    </div>
                                    <div class="col-12 mb--20">
                                        <label>Password</label>
                                        <input type="password" placeholder="Your Password" name="password" required>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="check-box">
                                            <input type="checkbox" id="remember_me">
                                            <label for="remember_me">Remember me</label>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="forgotton-password_info">
                                            <a href="{% url 'userauths:request_reset_email' %}"> Forgotten password?</a>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <button type="submit" class="uren-login_btn">Login</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                        <div class="banner-item img-hover_effect">
                            <br><br><br>
                            <center>
                                <div class="banner-content">
                                    <h3>New Member ?</h3>
                                    <p>Welcome To Our MarketPlace. <span>Click button Below to Sign Up</span></p>
                                    <div class="uren-btn-ps_left">
                                        <a class="uren-btn" href="{% url 'userauths:sign-up' %}" style="width:300px;" >Create New Account</a>
                                    </div>
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- E-MariStore Login Register Area  End Here -->
        {% endblock content %}

templates/userauths/customeractivate.html
{% autoescape off %}

Hi, {{user.full_name}} Thanks for registering as a Customer on the marketplace.

please click This link below to verify your account

http://{{domain}}{% url 'userauths:customeractivate' uidb64=uid token=token %}


{% endautoescape%}

templates/userauths/profile_update.html
{% extends 'partials/base.html' %} {% load l10n humanize %}
{% load static %}
{% block content %}

<body class="template-color-1">
    <div class="breadcrumb-area">
        <div class="container">
            <div class="breadcrumb-content">
                <h2>Other</h2>
                <ul>
                    <li><a href="{% url 'Home' %}">Home</a></li>
                    <li class="active">My Account</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- E-MariStore Breadcrumb Area End Here -->
    <!-- Begin E-MariStore Page Content Area -->
    <main class="page-content">
        <!-- Begin E-MariStore Account Page Area -->
        <div class="account-page-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3">
                        <ul class="nav myaccount-tab-trigger" id="account-page-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="account-profile-tab" data-toggle="tab" href="#account-profile" role="tab" aria-controls="account-profile" aria-selected="true"><img src="{% static 'assets/images/banner/user.png' %}" alt="dashboard" width="20px">&nbsp;Profile</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link" id="account-logout-tab" href="{% url 'userauths:custom_logout' %}" role="tab" aria-selected="false"><img src="{% static 'assets/images/banner/logout.png' %}" alt="dashboard" width="20px">&nbsp;Logout</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-9">
                        <div class="tab-content myaccount-tab-content" id="account-page-tab-content">
                            <div class="tab-pane fade show active" id="account-profile" role="tabpanel" aria-labelledby="account-profile-tab">
                                <div class="myaccount-profile border-bottom">
                                    <h3>Update Profile</h3>   
                                </div>
                                {% if form.errors %}
                                <div class="alert-danger">
                                    <strong>{{ form.errors }}</strong>
                                </div>
                                {% endif %}
                                <div class="myaccount-details">
                                    <form action="#" class="uren-form" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="uren-form-inner">
                                            <div class="single-input">
                                                {% if profile.profile_image %}
                                                <img src="{{ profile.profile_image.url }}" alt="" width="100px" style="border-radius: 50%;">
                                                {% else %}
                                                <img src="{% static 'assets/images/banner/default.png' %}" alt="" width="100px" style="border-radius: 50%;">
                                                {% endif %}
                                            </div>
                                            <div class="single-input">
                                                {{ form.profile_image }}
                                            </div>
                                            <div class="single-input">
                                                {{ form.full_name }}
                                            </div>
                                            <div class="single-input">
                                                {{ form.bio }}
                                            </div>
                                            <div class="single-input">
                                                {{ form.phone }}
                                            </div>
                                            <div class="single-input">
                                                <button class="uren-btn uren-btn_dark" type="submit"><span>Save Changes</span></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- E-MariStore Account Page Area End Here -->
    </main>
</body>


{% endblock content %}

templates/userauths/request_reset_email.html
{% extends 'partials/base.html' %} {% load l10n humanize %}
{% load static %}
{% block content %}


<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
        
            <header class="mb-4"><h4 class="card-title">Request a link to activate</h4></header>
            <form action="{% url 'userauths:request_reset_email' %}" method="POST">
                {% csrf_token  %}
                    <div class="form-row">
                        <div class="col form-group">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" required>
                              
                        </div> <!-- form-group end.// -->
                </div>
                <br>
                    <div class="form-group">
                        <button type="submit" name="" class="btn uren-btn_dark btn-block"> Send link </button>
                    <!-- form-group// -->
        
                </form>
                <p class="mt-2">Go Back <a href="{% url 'userauths:custom_login' %}">Login</a></p>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        
    
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
   {% endblock content %}

templates/userauths/reset_user_password.html
{% autoescape off %}

Hi there please click the link below to reset your password kindly


http://{{domain}}{% url 'userauths:set_new_password' uidb64=uid token=token %}





{% endautoescape %}

templates/userauths/set_new_password.html
{% extends 'partials/base.html' %} {% load l10n humanize %}
{% load static %}
{% block content %}


<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
        
            <header class="mb-4"><h4 class="card-title">Set new password</h4></header>
            <form action="{% url 'userauths:set_new_password' uidb64 token %}" method="POST">{% csrf_token  %}
                

                
         
    
    
                    <div class="form-row">
                        <div class="col form-group">
                            <label>New Password</label>
                            <input type="password" name="password" class="form-control" placeholder="enter new password" required>
                              
                        </div> <!-- form-group end.// -->
                    </div> 
                    <div class="form-row">
                        <div class="col form-group">
                            <label>Confirm Password</label>
                            <input type="password" name="confirm_password" class="form-control" placeholder="confirm new password" required>
                              
                        </div> <!-- form-group end.// -->
                    </div> 
                    <div class="form-group">
                        <button type="submit" name="" class="btn btn-outline-danger btn-block"> Reset  </button>
                    <!-- form-group// -->
        
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
{% endblock content %}

templates/userauths/vendoractivate.html
{% autoescape off %}

Hi, {{user.full_name}} Thanks for registering as a seller on the marketplace.

please click This link below to verify your account

http://{{domain}}{% url 'userauths:vendoractivate' uidb64=uid token=token %}


{% endautoescape%}